ReadGMM <- function(GMMfile, GMMdir){
   # V = ReadGMM(GMMfile,GMMdir);
   # einlesen eines multivariaten GMM modells 
   # 
   # INPUT
   # GMMfile        Output File name
   # GMMdir         Output File Directory
   # 
   # OUTPUT
   # Means(1:AnzVar,1:MaxNrGaussFound)         means of GMM generated by EM algorithm
   # Sdevs(1:AnzVar,1:MaxNrGaussFound)         standard deviations of GMM generated by EM algorithm
   # Weights(1:AnzVar,1:MaxNrGaussFound)       prior probabilities of Gaussians
   # GMMheader(1:MaxNrGaussFound)              names of the Modes typically G1,...Gn
  
  V <- ReadLRN(GMMfile, GMMdir)
  GMMData = V$Data
  GMMKey = V$Key
  GMMHeader = V$Header
  
  MInd = which(GMMKey<100)
  SInd = which((GMMKey >= 100)  & (GMMKey < 1000))
  WInd = which(GMMKey >= 1000)
  
  KeyOK = (length(MInd) == length(SInd)) && (length(MInd) == length(WInd))
  if(KeyOK){
    Means = GMMData[MInd,]
    Sdevs = GMMData[SInd,]
    Weights = GMMData[WInd,]
  } else stop("ReadGMM: Nr of Means, Sdevs and Weights is not equal.")
  
  return(list(Means = Means, Sdevs = Sdevs, Weights = Weights, GMMheader = GMMHeader))
}