WriteGMM <- function(GMMfile, GMMdir, Means, Sdevs, Weights){
 # V <- WriteGMM(GMMfile,GMMdir,Means,Sdevs,Weights);
 # ausschreiben eines multivariaten GMM modells, die 
 # 
 # INPUT
 # GMMfile        Output File name
 # GMMdir         Output File Directory
 # Means(1:AnzVar,1:MaxNrGaussFound)         means of GMM generated by EM algorithm
 # Sdevs(1:AnzVar,1:MaxNrGaussFound)         standard deviations of GMM generated by EM algorithm
 # Weights(1:AnzVar,1:MaxNrGaussFound)       prior probabilities of Gaussians
  
  # Beispiel Daten
  # Means
  # 1	5	8	4
  # 6	4	3
  # 1	
  # 8	5
  # 
  # |    -> Anzahl Moden
  # V Anzahl Variablen
  
  if(is.matrix(Means)){
    NrOfGauss = ncol(Means)
    AnzVar = nrow(Means)
  } else{
    NrOfGauss = length(Means)
    AnzVar = 1
  }
  
  GMMheader = paste0("G", 1:NrOfGauss)
  GMMkey = c(1:AnzVar , 100 + (1:AnzVar) , 1000 + (1:AnzVar))  # bloecke fuer means, sdevs und weights
  GMMData = rbind(Means, Sdevs, Weights)
  Comment = "Multinomial Gauss Mixtur Modell, GMMData = [Means;Sdevs;Weights], Means(1:NrOfVariables,MaxNrGaussFound). (R impl.)"
  WriteLRN(GMMfile, GMMData, GMMheader, GMMkey, OutDirectory = GMMdir, CommentOrDigits = Comment)
}